name: App Docker build and push
on:
  push:
    branches:
      - main
      - jack_develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push register app session II
        uses: docker/build-push-action@v3
        with:
          context: hands-on/session II/
          push: true
          file: ./hands-on/session II/Materials/Dockerfile
          tags: ${{ secrets.DOCKERHUB_ORG }}/nsdf_tutorial:sessionII

      - name: Build and push register app session III
        uses: docker/build-push-action@v3
        with:
          context: hands-on/session III
          push: true
          file: ./hands-on/session III/Dockerfile
          tags: ${{ secrets.DOCKERHUB_ORG }}/nsdf_tutorial:sessionIII

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
